Repository UBC-MDS/quanteda, pull requests merged in 2024-02, with the labels that each got.

#83 Feedback: Added repostatus badge to readme
  README.md
Labels: feedback

#91 Fixed issue with plot_num_dist tests
  src/quanteda/plot_num_dist.py
  tests/test_plot_num_dist.py
Labels: feedback

#95 Update generate return series
  src/quanteda/generate_return_series.py
  tests/test_generate_return_series.py
Labels: feedback

#97 fix: address feedback by modifying the package description
  README.md
Labels: feedback

#98 fix: Feedback addressed by adding instructions for cloning repo by HTTP
  README.md
Labels: feedback

#100 fix: Feedback addressed by adding a testing the edge case in plot_missing_vals
  tests/test_plot_missing_vals.py
Labels: feedback

#99 adjusted the README a little bit
  README.md
Labels: documentation

#101 feat!: release 3.0.0
  pyproject.toml
Labels: enhancement
