Repository UBC-MDS/quanteda, pull requests merged in 2024-01, with the labels that each got.

#20 Adding financial metrics function
  src/quanteda/financial_metrics.py
Labels: functionality

#31 create test data, unit tests and function body for `generate_return_series`
  environment.yml
  poetry.lock
  src/quanteda/generate_return_series.py
  tests/conftest.py
  tests/test_generate_return_series.py
Labels: documentation, enhancement

#38 Added test coverage dependency
  poetry.lock
  pyproject.toml
Labels: enhancement

#36 Update docs
  CHANGELOG.md
  README.md
  environment.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#39 fixed the typo in environment.yml
  environment.yml
Labels: bug

#54 Update .readthedoc.yml
  .readthedocs.yml
  docs/example.ipynb
  pyproject.toml
Labels: bug

#64 Setup CI/CD
  .github/workflows/ci-cd.yml
  pyproject.toml
Labels: enhancement

#67 fix: add release token for the CD
  .github/workflows/ci-cd.yml
Labels: bug

#68 fix: correct changelog version number
  CHANGELOG.md
Labels: bug
